spot:
  BTC-USDT-SPOT: BTC-USDT
  ETH-USDT-SPOT: ETH-USDT
  BNB-USDT-SPOT: BNB-USDT
  XRP-USDT-SPOT: XRP-USDT
  SOL-USDT-SPOT: SOL-USDT

perp:
  BTC-USDT-SWAP: BTC-USDT-SWAP
  ETH-USDT-SWAP: ETH-USDT-SWAP
  BNB-USDT-SWAP: BNB-USDT-SWAP
  XRP-USDT-SWAP: XRP-USDT-SWAP
  SOL-USDT-SWAP: SOL-USDT-SWAP
  ADA-USDT-SWAP: ADA-USDT-SWAP
  DOGE-USDT-SWAP: DOGE-USDT-SWAP
  MATIC-USDT-SWAP: MATIC-USDT-SWAP
  DOT-USDT-SWAP: DOT-USDT-SWAP
  LTC-USDT-SWAP: LTC-USDT-SWAP
  TRX-USDT-SWAP: TRX-USDT-SWAP
  AVAX-USDT-SWAP: AVAX-USDT-SWAP
  LINK-USDT-SWAP: LINK-USDT-SWAP
  ATOM-USDT-SWAP: ATOM-USDT-SWAP
  FIL-USDT-SWAP: FIL-USDT-SWAP
  APT-USDT-SWAP: APT-USDT-SWAP
  NEAR-USDT-SWAP: NEAR-USDT-SWAP
  SAND-USDT-SWAP: SAND-USDT-SWAP
  AAVE-USDT-SWAP: AAVE-USDT-SWAP
  UNI-USDT-SWAP: UNI-USDT-SWAP