spot:
  BTC-USDT-SPOT: BTCUSDT
  ETH-USDT-SPOT: ETHUSDT
  BNB-USDT-SPOT: BNBUSDT
  XRP-USDT-SPOT: XRPUSDT
  SOL-USDT-SPOT: SOLUSDT

perp:
  BTC-USDT-SWAP: BTCUSDT
  ETH-USDT-SWAP: ETHUSDT
  BNB-USDT-SWAP: BNBUSDT
  XRP-USDT-SWAP: XRPUSDT
  SOL-USDT-SWAP: SOLUSDT
